---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Profile
metadata:
  name: spring-cloud-dev
  description: >
    Installs Spring Cloud Gateway, Config Server and Service Registry as available application infrastructure for your cloud native application architecture for development environments.
    With Spring Cloud profile, you can take advantage of our self-service, enterprise API gateway, configuration delivered at runtime and enhanced service discovery for all Spring applications deployed to the space.
spec:
  requiredCapabilities:
    - name: application-configuration-service.tanzu.vmware.com
    - name: service-registry.spring.tanzu.vmware.com
    - name: spring-cloud-gateway.tanzu.vmware.com
  traits:
    - name: application-configuration-service-trait
      alias: application-configuration-service-trait
      values:
        inline:
          configurationSource:
            backends:
              - uri: <https-git-repo-configuration-url>
    - name: service-registry-trait
      alias: service-registry-trait
    - name: spring-cloud-gateway-dev-trait
      alias: spring-cloud-gateway-dev-trait