---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Profile
metadata:
  name: spring
  description: Configure a Spring Gateway to ensure the health, performance, and security of your Spring app running in a Space. A Space provisioned with this profile will be able to deploy a stateless Spring app and setup internal ingress to reach the app.
spec:
  #! requiredCapabilities:
  #! - name: package-management.tanzu.vmware.com
  traits:
    - name: server-workload
      alias: server-workload
      values:
        inline:
          server-workload-installer.tanzu.vmware.com:
            #! Service account name to be created and granted permissions, associating it with RBAC rules for server workloads.
            serviceAccountName: server-workload-installer
          workload-imagepull-secret.tanzu.vmware.com:
            #! name of ImagePullSecret to be associated with workload serviceAccount.
            secretName: workload-imagepull-secret
            #! Service account used for running the workload.
            serviceAccountName: default
    - name: public-ingress
      alias: public-ingress
    - name: spring-cloud-gateway
      alias: spring-cloud-gateway
