apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Trait
metadata:
  name: egress #Unique Name of the Trait
  description: Egress enable Developers and Operators to publish Space Services to out-of-the-Space consumers (users or workloads). To achieve this outcome, an ingress gateway is required and a Space must be selected.
spec:
  carvelPackages:
    - alias: egress.tanzu.vmware.com
      refName: egress.tanzu.vmware.com
      values:
        inline:
          hosts:
            - host: <hostValue> #The host value is the domain name of the service to be accessed
              name: <hostName> #Unique Name of the Host
              ports:
                - name: https #Name of the Port
                  number: 443 #Port Number
                  protocol: HTTPS #Protocol Type(HTTP/HTTPS/TCP)
          open: false #Open/Restricted Egress Policy mode
      versionSelection:
        constraints: 0.0.1 #For Beta 2, current version is 0.0.1. Ensure to keep it updated.
