apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Trait
metadata:
  name: public-ingress
spec:
  description: Ingress enable Developers and Operators to publish Space Services to out-of-the-Space consumers (users or workloads). To achieve this outcome, an ingress gateway is required and a Space Service must be selected.
  carvelPackages:
    - alias: multicloud-ingress.tanzu.vmware.com
      refName: multicloud-ingress.tanzu.vmware.com
      versionSelection:
        constraints: <multicloud-ingress.tanzu.vmware.com-version> #For Beta 2, the version of the multicloud-ingress.tanzu.vmware.com package is 0.0.12. Ensure to keep the version updated.
      values:
        inline:
          name: default-gateway
          domain: test.devframework.land
          listenerTemplates:
            - namePrefix: https-
              port: 443
              protocol: HTTPS
              tls:
                secretRef: prod-certs
            - namePrefix: http-
              port: 80
              protocol: HTTP
          gslb:
            provider: AWS
            hostedZoneId: <hostedZoneIdValue>   #AWS HostedZone is a container of DNS record for a domain. HostedZoneId is AWS generated id for a domain.
            authentication_type: AUTH_TOKEN
            authentication: #This will eventually be replaced/removed when the Credentials Manager is in place.
              credsRef: <aws secret name> #Name of the secret created in the project workspace consisting of aws access_key, secret_access_key and session_token.
              region: <region>      #Region
      excludedKeys:
        - domain
        - listenerTemplates