---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Trait
metadata:
  name: service-registry-trait
  description: Service Registry provides an app Service Discovery pattern, one of the key benefits of a microservice-based architecture.
spec:
  carvelPackages:
    - alias: service-registry-installer.spring.apps.tanzu.vmware.com
      refName: service-registry-installer.spring.apps.tanzu.vmware.com
      versionSelection:
        constraints: 1.0.1
      values:
        inline:
          eurekaServer:
            replicas: 2
            imagePullSecretName: spring-cloud-gateway-image-pull-secret