---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Trait
metadata:
  name: service-registry-trait
spec:
  carvelPackages:
    - alias: service-registry-installer.spring.apps.tanzu.vmware.com
      refName: service-registry-installer.spring.apps.tanzu.vmware.com
      versionSelection:
        constraints: 1.0.1
      values:
        inline:
          eurekaServer:
            replicas: 2
            imagePullSecretName: <image-pull-secret>