---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Trait
metadata:
  name: server-workload
  description: Server Workload define the specific characteristics and requirements of applications or services running on the cluster.
spec:
  carvelPackages:
    - refName: server-workload-installer.tanzu.vmware.com
      alias: server-workload-installer.tanzu.vmware.com
      versionSelection:
        constraints: "0.1.0-alpha.4"
        inline:
          #! List of image pull secrets to be added to the Service Account.
          imagePullSecrets: []
          #! Service account name to be created and granted permissions, associating it with RBAC rules for server workloads.
          serviceAccountName: server-workload-installer
      excludedKeys:
        #! - serviceAccountName
        - imagePullSecrets
    - refName: workload-imagepull-secret.tanzu.vmware.com
      alias: workload-imagepull-secret.tanzu.vmware.com
      versionSelection:
        constraints: "0.1.0-alpha.3"
      values:
        inline:
          #! name of ImagePullSecret to be associated with workload serviceAccount.
          secretName: workload-imagepull-secret
          #! Service account used for running the workload.
          serviceAccountName: default
      #! excludedKeys:
      #! - secretName
      #! - serviceAccountName
