---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Trait
metadata:
  name: spring-cloud-gateway-dev-trait
  description: >
    Define the configurations for a Spring Cloud Gateway to provide a simple and effective route to APIs for development environments.
    Create a useful separation of concern for platform operators to standardize the gateway setup.
spec:
  carvelPackages:
    - alias: spring-cloud-gateway-installer.tanzu.vmware.com
      refName: spring-cloud-gateway-installer.tanzu.vmware.com
      versionSelection:
        constraints: 1.0.0
      values:
        inline:
          count: 1  # DevMode for development spaces, removes cluster synchronization.
                    #
                    # Setting count to > 1 will create individual instances that do NOT share
                    # sso session and rate-limiting counters.
                    # For production (with cluster synchronization enabled) configure remove
                    # configuration keys below and add a Redis binding.
                    # ```
                    #  bindings:
                    #    redis:
                    #     secret: <redis-configuration-secret>
                    # ```
          java-opts: "-Dcom.vmware.tanzu.springcloudgateway.dev.mode.enabled=true"
          env:
            - name: com.vmware.tanzu.springcloudgateway.clustering.enabled # Requires SCG-K8s v2.1.9
              value: false
