---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Trait
metadata:
  name: spring-cloud-gateway-dev-trait
  description: >
    Define the configurations for a Spring Cloud Gateway to provide a simple and effective route to APIs.
    Create a useful separation of concern for platform operators to standardize the gateway setup.
spec:
  carvelPackages:
    - alias: spring-cloud-gateway-installer.tanzu.vmware.com
      refName: spring-cloud-gateway-installer.tanzu.vmware.com
      versionSelection:
        constraints: 1.0.0

