---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Trait
metadata:
  name: spring-cloud-prod-trait
  description: >
    Installs Spring Cloud Gateway, Config Server and Service Registry as available application infrastructure for your cloud native application architecture.
    With Spring Cloud profile, you can take advantage of our self-service, enterprise API gateway, configuration delivered at runtime and enhanced service discovery for all Spring applications deployed to the space.
spec:
  carvelPackages:
    - alias: application-configuration-service-installer.tanzu.vmware.com
      refName: application-configuration-service-installer.tanzu.vmware.com
      versionSelection:
        constraints: 1.0.1
      values:
        inline:
          configurationSource:
            backends:
            - uri: <https-git-repo-configuration-url>
    - alias: service-registry-installer.spring.apps.tanzu.vmware.com
      refName: service-registry-installer.spring.apps.tanzu.vmware.com
      versionSelection:
        constraints: 1.0.1
      values:
        inline:
          eurekaServer:
            replicas: 2
            imagePullSecretName: <image-pull-secret> # If not provided, can use same as SCG
    - alias: spring-cloud-gateway-installer.tanzu.vmware.com
      refName: spring-cloud-gateway-installer.tanzu.vmware.com
      versionSelection:
        constraints: 1.0.0
      values:
        inline:
          count: 2 # Minimum to test clustering features
          bindings:
            redis:
              secret: <redis-configuration-secret> # Must be provided externally for multi-region setup https://docs.vmware.com/en/VMware-Spring-Cloud-Gateway-for-Kubernetes/2.1/scg-k8s/GUID-guides-redis.html